# Introduction {#intro}

This landscape report examines the scientific and patent landscapes for marine genetic resources in the South East Asia (ASEAN region).^[ASEAN stands for the Association of Southeast Asian Nations. For more information on ASEAN visit [https://asean.org/](https://asean.org/)] The aim of the report is to advance knowledge and understanding of the importance of research and innovation involving the marine environment in the ASEAN region. 

It has recently been estimated that South East Asia is home to around a third of the world's population and that 70 percent of its residents live in coastal areas [Olewiler in @Marine_2016]. While encompassing approximately 10% of the world's land mass, the ASEAN region includes an estimated 30% of the world's coral reefs and 33% of its mangrove forests [@Marine_2016]. Fisheries are also central to the livelihoods of many people within the ASEAN region with recent estimates suggesting that the region accounts for 21 million tonnes of fish production, or a quarter of global production [Ferrer in @Marine_2016]. As this suggests the marine environment and the ecosystem services that it provides are central to the economies, livelihoods and welfare of people throughout the ASEAN region. Recent years have witnessed growing research and awareness of the threats to the marine environment in the form of pollution, over-exploitation of marine resources and climate change [@Marine_2016].

Growing awareness of human impacts on the marine environment has also been accompanied by increased recognition of the opportunities that the marine environment presents for advancing human welfare through the development of new products such as pharmaceuticals, cosmetics, novel foods and tools for use in biotechnology. Awareness of the actual and potential contribution of the marine environment to economic well being is increasingly taking shape through the adoption of policies directed towards the 'Blue economy' within ASEAN and the wider East Asia region [@Gamage_2016]. Thus, in 2012 countries from across the region issued the *Changwon Declaration: Towards an Ocean-based Blue Economy* which stated that: 

>"We understand the Blue Economy to be a practical ocean-based economic model using green infrastructure and technologies, innovative financing mechanisms and proactive institutional arrangements for meeting the twin goals of protecting our oceans and coasts and enhancing its potential contribution to sustainable development, including improving human well-being and reducing environmental risks and ecological scarcities."^[Source: PEMSEA [http://www.pemsea.org/sites/default/files/changwon-declaration.pdf](http://www.pemsea.org/sites/default/files/changwon-declaration.pdf)]

On a wider level, growing awareness of the threats to the marine environment and its role in human welfare and global ecosystem services is reflected in ongoing work under the marine programme of work of the United Nations Convention on Biological Diversity and negotiations under the United Nations General Assembly on a new treaty on biodiversity in Areas Beyond National Jurisdiction. 

This landscape report seeks to contribute to understanding scientific research and patent activity involving marine genetic resources in South East Asia. The landscape is based on a review of data from 391,181 scientific publications from the South East Asian region and 461,380 patent documents. The research involved text mining these documents for over 398,000 marine species recorded in the World Register of Marine Species^[World Register of Marine Species [http://www.marinespecies.org/](http://www.marinespecies.org/)] and access to millions of species occurrence records from the Global Biodiversity Information Facility (GBIF).^[Global Biodiversity Information Facility (GBIF) [https://www.gbif.org/](https://www.gbif.org/)] 

The research reveals that marine genetic resources are a growing focus of attention among research communities within the ASEAN region. Research on marine genetic resources within the region is primarily oriented towards the aquaculture sector but extends to the exploration of the potential of marine organisms as sources of new pharmaceuticals, cosmetics and other products. In addition, a significant body of research is dedicated to understanding the basic biology of marine organisms and the environmental impacts of human activity. The report reveals that marine genetic research in the ASEAN region is increasingly international in nature. We identify collaborations between researchers from over 130 countries and an emerging network of funding agencies from within and across the region. While marine organisms have attracted an increasing amount of commercial interest as sources of potential new products in recent years, as in many regions of the world, patent activity is presently emergent for marine genetic resources in the ASEAN region and concentrates on the aquaculture and, to a lesser degree, the pharmaceutical sectors.

The report begins with a general overview of biodiversity data for the ASEAN region to orient the reader on available knowledge about the region. We then move into analysis of the scientific and patent landscapes for marine genetic research within the ASEAN region. 

The report is organised into four sections. 

1. Biodiversity Data in the ASEAN region
2. The Scientific Landscape
3. The Patent Landscape
5. Conclusions

Annex 1 presents a summary of activity for some of the major species identified in the report and links to additional resources. Annex 2 presents details of the methodology used to prepare the report. The bibliography provides details and links to the research reviewed for this report. 
