# Conclusion

This landscape report has examined the scientific and patent landscapes for marine genetic resources in Southeast Asia. The marine environment and marine genetic resources play a vital role in the livelihoods and welfare of people throughout Southeast Asia. Southeast Asia also possesses an estimated 30% of the world's coral reefs and 33% of its mangrove forests. In the context of concerns about the conservation and sustainable use of biodiversity this makes clear that marine genetic resources are of central importance to livelihoods within the region and to wider international efforts to conserve biodiversity. 

In seeking to assess the status of the marine environment and assess opportunities for potential economic development a key constraint confronting many countries within and outside the region is a lack of basic taxonomic information. In the case of Southeast Asia the Global Biodiversity Information Facility in mid-2018 contained over 6.3 million species observation records for 147,036 species. As a region possessing three countries characterised as megadiverse (Indonesia, Malaysia and the Philippines) existing data is likely to represent only a small percentage of wider biodiversity within the region. Improving the availability of basic taxonomic information through the digitisation of existing collections and investments in basic taxonomic research has an important role to play both in improving understanding of biodiversity and contributing to the pursuit of a sustainable blue economy in the region. 

Patent landscape analysis typically focuses only on the analysis of patent documents. This report has sought to broaden our understanding of research and innovation by starting with analysis of the scientific landscape in the Southeast Asia region. This revealed a landscape of over 6,000 scientific publications involving 3,685 marine species and a global network involving approximately 17,736 researchers from nearly 4,000 organisations in 136 countries. Our analysis revealed that research activity for marine genetic resources is growing in the majority of ASEAN countries. Research ranges from basic taxonomic and ecological research to a major focus on aquaculture and concentrations of research effort in marine natural products in biotechnology and pharmaceuticals. The available data on funding reveals the central importance of national research funding agencies along with an important network of international funding agencies from Japan, China, the United States and Europe. When viewed from a regional perspective and strategies for the pursuit of a blue economy, this suggests the possibility of funding bodies within the ASEAN region exploring options to coordinate to identify priority research issues for marine genetic research in areas such as conservation, sustainable use and innovation.

The review of the patent landscape for marine genetic resources in the ASEAN region identified significant issues in access to data in national patent collections. Access to patent data, notably full text collections, is an important precondition for patent analytics such as generating patent statistics and examining trends in specific technology areas. In the case of marine genetic resources we identified 3,587 priority first filings of patent applications linked to 42,857 family members worldwide containing 3,114 species. The total number of filings, as an indicator of investments in research and development, suggest that patent activity for marine genetic resources in the ASEAN region is presently emergent. In particular, at the level of marine species the analysis revealed the prominence of aquaculture focused filings in existing patent activity that mirrors the emphasis on aquaculture as a focus of scientific research in the region. However, viewed in terms of technology, the main focus of patent activity was concentrated in biotechnology, pharmaceuticals, peptides and biocides. 

Building on analysis of the scientific landscape in the ASEAN region, the report explored patent activity by researchers within the ASEAN region. In total we identified 290 authors from the region who are also inventors in 369 patent applications involving 446 marine species. Analysis of filings by researches revealed a concentration of effort in areas such as conotoxins from sea snails, aquaculture, vaccines, endotoxins, biofouling compositions, microsatellite markers, nutraceuticals from jellyfish, cytokine receptors in plants, carrageenan from algae, toxins from sea anemones, biopigments and biofilms, Alzheimers disease and the bioactive properties of sea urchins, marine sponges and starfish. The number of researchers from the ASEAN who are involved in patent activity is small when compared with the wider scientific landscape, however these researchers form a potential pool of experienced specialists from whom other researchers interested in the broader dissemination and application of their work may learn. 

The analysis presented in this report is intended to contribute to wider debates within the ASEAN region on appropriate strategies for promoting recognition of the importance of marine biodiversity and related traditional knowledge for livelihoods and welfare in the region. As we have seen in the course of this report, important research is taking place on marine organisms in connection with issues such as heavy metal and other contaminants in the marine environment that reflect the impacts of human activity upon the marine environment. At the same time research on the traditional uses of marine and coastal species is providing guidance on the potential development of new products while other research focuses on biological alternatives to environmental toxic biofouling compositions. As such, scientific research within the ASEAN region both serves to demonstrate the importance of genetic resources for innovation while highlighting a need to address the enduring challenge of the conservation and sustainable use of biodiversity. 
